apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    version: 2.0.0
    repo: https://charts.external-secrets.io
    namespace: auth
    includeCRDs: true

# Add this patch to inject the ArgoCD sync option into the CRDs
patches:
  - target:
      kind: CustomResourceDefinition
      name: ".*\\.external-secrets\\.io" # Regex to match all ESO CRDs
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true