apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-layer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com:BoraPerusic/k3s-df.git'
    targetRevision: HEAD
    path: platform/data # We will create this folder
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true