apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-pull-secret-services
  namespace: services
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: acr-pull-secret-services
    namespace: services
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "tatrman.azurecr.io": {
                "username": "{{ .client_id }}",
                "password": "{{ .client_secret }}",
                "auth": "{{ printf "%s:%s" .client_id .client_secret | b64enc }}"
              }
            }
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: acr-client-id
    - secretKey: client_secret
      remoteRef:
        key: acr-client-secret