apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

helmGlobals:
  chartHome: ../../../../../blueprints

# 1. Define the Helm Chart to inflate
helmCharts:
  - name: microservice
    version: 1.0.0
    releaseName: llm-gateway
    namespace: infra
    valuesFile: values.yaml

configMapGenerator:
  - name: bp-dsk-env
    envs:
      - ../../../../../clusters/bp-dsk/bp-dsk.env

generatorOptions:
  disableNameSuffixHash: true

resources:
  - sealed-llm-gateway-creds.yaml