---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-gateway-creds
  namespace: auth
spec:
  encryptedData:
    azure-openai-api-key: AgC80O2J4YO0cFH6x4lzIrlgxCgMtGhvYz3qUPTXffNujoCsN9wFiqwFDAJOGNf1ftNt0luAYZqRY3ohFzFKEiANC43rZEx/WNUtclGhHwXfix81nwqqtKy0Kc/8X47LHXT18/3BeZuese+poQGsSy4rg4Pi248v5bA9vbFzTQeuwrF2TtfUJixAAabqH4AnX+Gn8lZuSba2SBUJDjKCEcmqLJj2BcH2Tex42tegeppOe0YJqQMoRZcxkIFaVPAKmEk6Bj3uuh6P0dsZeNEOtEalAg+zj7gz8f1N1q3rntDzCy/+27/uX+WXfK2fjK+E9Ck6c9HxtmwNddVF9wKUDGYL8rEbhIET7TTWRQUmL1Lu8eEB7g2HC6bDB7iadVQKeFi2OwnBArNEI/nW4A4mUOad1zL8OobQ8SbCS+QBbIL5p/UUcH96M20oCcvAome113ATNv3BCYtOpQ8HMdeI0uszunbWL8pLKeWvfy8K4h9iQ+kLsrk8uVRtfq7MVqWiSrAp/y4YWWvjoHBTg/vJW5dBFIVjcsW3gf+NDCe0oySByROIIaPNxiF5/ubviPLg202maVRuUidgeJKnR1HxHbtjJJV3Fw5yMPuoYNabmNyQZuyaUru5GkowVCyyOq86ngd3xH6W1rJTLvXkmq/f3tOeRcnFx83OPvXDZJs2v/3JoMyWx2Qb8IlNiI+ZJBaTbS19kFIBaKf88oEw6VWPe74i5YLt0XjMnAx1NNhVNjYtjw==
    llm-gtw-db-password: AgBwnAKcnHMKlSaIE/AQo8oLkzw8VPk1LNFKJrzgV+VgFW1s21i2VKpYiYCtL4kV4Lgw9eVcgx5w6B/GOIRaxGHxi8KZnDzJ/UGufZXbC0RkEa7VsZ9djaiYrwaM81sq9M8OoCuiKK+uQRoKMNwMIOcjfcJ1YnYzrIjAD6c1deL0Y8eRVHbgPL4kCzWdR7jmidVVMyZD5UzY6jmUK9mEEH3N4UhqXd0GZ7QB3OKsNIe0cklAdUo4voeaCeYnQVBa3QZQTTxP6DSWRsvQW2nLp/WCPk711lQ38Y1iXUwLT5YH4FSPW+sXSMgSxiFykX1nTcAG/q1iNMDQ3XIIDxwa63h+zCnDfkhW6CZaJfxJk3rlDi3JoyR7LZrQan/ln6BJM5mx7tY6jZ9zkBK5V4k2RAgwhsPx32JWhDieKzBqpZfOWUnRDmILgjkXZFR+nyTEjCbj9F1SSp1GIRjes1OkVfllemKMqaCgzbPreuBpef7VvLxV2DcScUBKWTJ8y6XA5DZiqBuB8ymjqXxA8flyqH0ivzc6q/BPOX2wRyC78tj5KkMchcHCvpDKTuD5VmC8IgHH8xQtNP24DcN1LEVwTR/AFitPfr64qHkgFhKMZoayrsAL2NM6+P297bd4ZYDGXIcGOUjh42IzF45l2YFEujNOItrrP79nntV/Gqa8/ivEUyu1IQuVyXcgSmcAEMbE2upZ7dn3PgY=
  template:
    metadata:
      name: llm-gateway-creds
      namespace: auth
