---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-gateway-creds
  namespace: auth
spec:
  encryptedData:
    azure-openai-api-key: AgCHvwMbJkfni+8w/JydLMYStPPd8cMCMUjq9y00YS/yQobA0WHE5L8goklbtblDMcA/tKeF8WttHfseZHQ0h/0a0gYTkjgjUQbMliGNJFmNTN0rM+7qWu1mOmEgkKJ0PRB8ePog1z7kG7jIwBY68gr0nc3XdJmFakAJ9yOQsP8v21ZyUoEN5IVdjrHnMxX5SS0HZf25AIOKGj5Ak9tLQBkOzVwaRvPPVwmO59Cf06lNnhj/PX3GtefH3N2PCv53hh0OUMlPKyD2TF/jvrA9BwZiTW0hfbNc3dHnUKKZXfCzT8a12QdYFXH7yjSAEn8QjBHsY54DQVi6ngO4CbTWvUeLDH81Fz6K2rFB49ObLrWnOcDsWd7LQBS9Tn30X1Ex0e8658Kbl7QGzySwqOo9M2PVg4o3ycZKUGcwVfSCQn8KnqXJPUHt/6FcfE3iqVZokQsS+F8fEzPSkb0Uc+epgDetSCQflq+lOalezn/V75jR3mdtQzgENo/jBoXmVCyVuPuK1XzGnfMDVI2nFKaMdu4Kra829/dMrb2vOG+CqBEFc5v6gKtPEADnSDFVWw+k3o/cHKq7xbpKYQTZdLrBF5gFLlXG01HC1QFO1u+vIGsxZz5bB9P/f/2Gxh0FtcNeRz2dp6NIN1w+Z76kadsOBdxusPEkg1pM9BMuZ3t3IZAot08ca4WVj8Ns07/UyeEFySGvd3TAmlPw2xl36X20eNW9ie5lABMaQahncqqrEOajEA==
    llm-gtw-db-password: AgCqc9XeGmWVRAYoeefcGcl1wCtdwrddh2EBsJyhLvNFjM08CkRiWKZJ4YDiUDFbu/ZXei+DdAgfHiovf7Y3jukP51Luq1oRcWLjvg7SS9SK4N4MjNHTr+AI8iwMTCYKMg7dnIeAKmm+enTdcL6IAj8+j050eHbrxBkh88aIAUFPg25v7EWrglDS0KDMqIuUvvC62AXIRXWRWky5GxVY3GPxeuJIxLn05BDguRZK2vUl3yicweqXYBoXtIYtWK8TqDA+pMOLwI/cq7eJDiy0S/RqotdraU4Nz1xGfFBP0cuUcSnKUL0GUoUlYIV+nFpB2DcCegp1O956RHZXWHpKu6TuyjjfzmEoS4wGLk9xW60gy132Jcc9g50SyxJ03716WCQ/hA3+BOLltUOyqvNkaqo4UpoIWe2eO8xOhopjrtdic2ibxLOv/fDZeDCW3UfUC3DlCBHAq/CpR5SXZQZv2YfOGH1uYdguo75V+a3M07hOKiOqEcbSUKLOJpdkslZf9343DyQCMLoO7PgTo0eQZFc75KnKo/P7t+k7ZQwcnRLp3InFXzK8H4Fy4ocdEAjmqURNuJhdIzB/kYDAmY0ElTVve6h+TD2zpPmTRYPShHN6xTZ2dMsm29cTvmHVWSevIWpvKH3cZ5MhKtJyQN+lcgSctzvQ9B8IUuEXcseftcAEv/Mupw2xFJ4k2WKkcJXoBh4t5MQK5iY=
  template:
    metadata:
      name: llm-gateway-creds
      namespace: auth
