---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-gateway-creds
  namespace: infra
spec:
  encryptedData:
    azure-openai-api-key: AgCUQ9tqsZQTXo8qpvfnPhN7oDEGqcNxtX2W2DITeBPnxhlIiF132T6LQ4+eJgYbJBqfslG9W+zUZ3WHY3rB2gDbIe2rhyiE9o4FlaLVSD38txao11aoMZOg/ODaOPSED5JLWu1biQGJQHM5+lQl4uoFkIE2lwk3Ge0PKlM76zEP5GLadigz4d1ER6sHb/tZza4RXjvchKYJTPYZsZ6GbTqC6WlE+aA8qMTTgZ2KilUlU5hHFNeaMV9FUh6OhQEB7lSwq4YRAiVf9dQ8qVSG+LtKPjwbJMbgxIFIoM0TPBXXUyOAvr7HHRNUGolmE8M4q3dzZ0aGLK9Hb/mCBY9GeuxPOBEUhXi9GLXbnndunTnyGTSADVsG4bm1ljuxheNEMPNpHJNdsZe9Njp1txfQ6pTkcrG52zyUS9zSUUwGwr5EdZVkE7s57imTGn4IyA5R3jQfwLdyfp9/I6KnrgLxNije41CkSO0WZEsRe6DipO4AL5Gzw4/ox3UbYeG4sd3UhFBIv/wPP/oBSeCWTIvho5QJZXLQox7O4FfW/0nbgRgn8dRZ2m8wp9eglpy20k98ldHPdoBV6CSnfl2T1/zincfXGfqEydqwWu/1Xa8oaALyEiLu0PCJWF8CUUy8NHBOa4WnogALYN8BXFQo7LKBlf+uz6W7Mxaw0TlMvXrEFCXNSNGwMvqv0RGgFIoZPlzDI8XvudvyD2El+1x8uH+uta5QN3hJk3r8kG/DblDtUqrL8Q==
    llm-gtw-db-password: AgA6ELyuNyxu87N9N33z2+ueXkGRFNxrZw+TkllQt8vXwi7aRXCAqwSYq2R9r3KiH8cEbphnhGIA93ZjZKssrr9HRY1VJHXuE5FAvL0JEjqlw1lHHhVVqiqIMf6Q6IjecDNEfCu8EDmCCuoVIeRgG+y9KmTELZrFrarpR1t0sdWigHGsUZJWV7/QEaYztolDTI856NuClriddAjK3KQ3ajm28RLbxZrNpF7A3XdmMfgbuuNva58HXVJsupdcrk9Ey4z7ULpThcYF1qt9pEvUavK51R3ZbwZ+1GauOkRkwfjYsQa4q81rwPo4rOXqPk5dI1t/MeT6JWW3mTtdLWicsyRkJ1XgCm0m+s/8GoH8BnaFiVRRhS+7mjmIT8X/aJh8Q7rfd2IdxnSlYNbTpJIAaWcXiUy5iP9g3HoQ0mCT6sCIKf1v05Lal36XUlrJ/epBYiJN66Forc5VruYKm6cq9CZyY7/GIDb1gV2+31dFcYQgc8CB7v2d6Nhn3hh+f9SM7h2+ldU9UFcyRss4KnuXHj05gOCTQeG3nrd1wQPdlsdKLYngNeeX5JtnwWjsszTdZcdozW8PFANfkLelzAiLc1jamTe1Te+hVc3L/hocmvbIN3cpppKUxGbGMYtMUudGH1leVxrwTPrX6WE5bevP6TRAzNSYYFrqAYU2e5aqUf4QvqOKNQ1JqhCp/lDFv6o1xfuAg/X+9Qo=
  template:
    metadata:
      name: llm-gateway-creds
      namespace: infra
