replicaCount: 1

image:
  repository: tatrman.azurecr.io/llm-gateway
  tag: "0.1.3"
  pullPolicy: Always

imagePullSecrets:
 - name: acr-pull-secret-infra

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 # Python/FastAPI usually runs on 8000

envFrom:
  - configMapRef:
      name: bp-dsk-env

env:
  LOG_LEVEL: "DEBUG"
  AZURE_OPENAI_API_KEY:
    valueFrom:
      secretKeyRef:
        name: llm-gateway-creds
        key: azure-openai-api-key
  LLM_GTW_DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: llm-gateway-creds
        key: llm-gtw-db-password