replicaCount: 1

image:
  repository: tatrman.azurecr.io/llm-gateway
  tag: "0.1.3"
  pullPolicy: Always

imagePullSecrets:
 - name: acr-pull-secret-infra

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 7101
      targetPort: 7101
    - name: grpc
      port: 7201
      targetPort: 7201

containerPorts:
  - name: http
    containerPort: 7101
    protocol: TCP
  - name: grpc
    containerPort: 7201
    protocol: TCP

envFrom:
  - configMapRef:
      name: bp-dsk-env

env:
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: AZURE_OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: llm-gateway-creds
        key: azure-openai-api-key
  - name: LLM_GTW_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: llm-gateway-creds
        key: llm-gtw-db-password