---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-creds
  namespace: auth
spec:
  encryptedData:
    password: AgCOwKoQ1LOoJYH1ksCjSLfMqdveccfC8qpsCraIwi5CFVuUpEYROj4hZ+W6UmJYqxODwFwdcfY6fwX8SD4dcIHZiqG7vdewfYZPTS6FtIPrDKmXLifuFr0YqAtjeNzAtF8Z6qUSWg+beINAE4JR6RMG6IghZYAo2T5MhdCfAwhMNlgDYH3b3foVjmEbEkT2Twj55i3MWTauPJUbjypApg7kb71QELn9IajdsLUzHnmPJRDWjVmZr87xri+4RAc/KUQGLZJ0ULU0uZ3MLJWAl0c5Tr7YY3yuYEvxrP5zWxB3EwRpZWsv1YKf+QIQXkYXGOGOCxLcqESFogwMqJ0Z88C7Ogtf236e9CXVQX/JHqPjcWOMCNdq9T7nyDz582qChXFdqstbcTU1WQoQJK/GR++7h2lroWPp39agUdodbEtgwXVXxRX9cMysa5hhlhjEEqSF6N5Ooun7eoDzd/kRtxfzfmGG2oC2tErHdhf1lBjinFiAn8d1Dh2BvPgRw7/8P0IHesoHLMIaoyShSDfApa09w+YrauHrKek2S1Heg16GXHVhGnH4NKNfTWvD3Ueq+SNxgz1rX0ne51cOejTiRtjJi5CxO6kfIKvTqEejHvRSGwRaSv8NNisZmh+8xpCu5oLTCzke2ry0TynF6qAZjXglDLNtFs+hBEnWicYTtcsfYRKV4QrEKBfvQT6UwYQw2IzTAWs6oDI44KSiCcIsdtrZ30w=
    postgres-password: AgAl/HQ1VfAhhMEEW6qASo+t4Bd/d9GLfbb8V+gnLiIpq3wntTgZ+4erRE4WaG5z1hfU7lgY/CxZ0RhTKCPD6IMfvU6Bqsbmd/xE3mP735PeKrvt7KRWmsO73f/RrikOq0nDpUXvstvxuZ62oSFag6FhUIKqTufQSLZZb5I16998pkWyy9Z9iQU4PFa7YQ949ZKOVy4vULE+HldHooLgPa6ZRQbVc+BVRNY0/6lG9+4Ja4ud3PGrTK8yUslv2ffGecv+RwqsjSRVCs1n7mV10TkXj2N7cK2gtCPIMYYzg1OgzzNu3v+bB67raxH7rjU6H5ayHkJz+7beYl1c2f0t5IXneoVzVTGCLAN6E24dENFG5RzaY21riePas+WvFk08weQz8xqMQ9vaPQzRzBsklYfDLERxdyOW+lC4wqVJPdu82TQHYsZ85LYlF0zDJKXJLBAmJv+pLrPS1SiqD9k3B0VBlwg6/iaxdk1dMZfFaOivQHNF2v58Vb2tgKHg31X6oRlHykJfkRe6eOpfoLSADVVXEvKIA3R8dINjdIH53v3nSPx448Gtrghexqd4RwxMdBC1WlLB9DI49hKMqoKBewCWwdIi/rpk9TipmWuuC9kRcR+6TjYHTcDkTEelvqjP528a/l6UYzogLbqRt9YITIOWrHcPM2VzkA+Ge1DIURBOnxyBoebQ8FF9aPXYO5BDQ5IIX5OFiGddrATjg47Yj79kHrxCtA==
  template:
    metadata:
      name: keycloak-db-creds
      namespace: auth
